<?php

return [
    'category_contexts' => [
        'home.all' => 'واجهة الكل - كل الفئات',
        'kids.category' => 'الأطفال - الفئة',
        'kids.0_12' => 'الأطفال - 0-12 شهر',
        'kids.12_24' => 'الأطفال - 12-24 شهر',
        'kids.3_6' => 'الأطفال - 3-6 سنوات',
        'gifts.category' => 'الهدايا - الفئات',
        'toys.category' => 'العاب وتعليم - الفئات',
        'mother.category' => 'مستلزمات الأمومة - الفئات',
        'care.category' => 'الصحة والعناية بالبشرة - الفئات',
        'accessories.category' => 'الاكسسوارات - الفئات',
        'shoes.category' => 'الأحذية - الفئات',
    ],

    'product_sections' => [
        'home.for_you' => 'الكل - من أجلك',
        'home.new' => 'الكل - الجديد',
        'home.offers' => 'الكل - العروض والعروض السريعة',
        'home.bestsellers' => 'الكل - أفضل المبيعات',
        'kids.for_you' => 'الأطفال - من أجلك',
        'kids.summer' => 'الأطفال - إطلالات الصيف',
        'kids.brands' => 'الأطفال - ماركات مختارة',
        'kids.characters' => 'الأطفال - شخصيات محبوبة',
        'kids.cotton' => 'الأطفال - قطن ناعم',
        'kids.family' => 'الأطفال - أطقم العائلة',
        'gifts.for_you' => 'الهدايا - من أجلك',
        'gifts.safe' => 'الهدايا - هدايا آمنة',
        'gifts.newborn' => 'الهدايا - مواليد جدد',
        'gifts.educational' => 'الهدايا - هدايا تعليمية',
        'gifts.wrapping' => 'الهدايا - تغليف لطيف',
        'gifts.popular' => 'الهدايا - الأكثر طلبا',
        'gifts.today' => 'الهدايا - هدايا اليوم',
        'gifts.new_arrivals' => 'الهدايا - وصل حديثا',
        'toys.for_you' => 'العاب وتعليم - من أجلك',
        'toys.safe' => 'العاب وتعليم - آمن للأطفال',
        'toys.brands' => 'العاب وتعليم - ماركات ألعاب',
        'toys.baby_kids' => 'العاب وتعليم - للرضع والصغار',
        'toys.educational' => 'العاب وتعليم - تعليم وتفكير',
        'toys.new_arrivals' => 'العاب وتعليم - وصل حديثا',
        'toys.deals' => 'العاب وتعليم - عروض الألعاب',
        'mother.for_you' => 'مستلزمات الأمومة - من أجلك',
        'mother.newborn' => 'مستلزمات الأمومة - حديثي الولادة',
        'mother.travel' => 'مستلزمات الأمومة - تنقل وخروج',
        'mother.comfort' => 'مستلزمات الأمومة - راحة الأم',
        'mother.organize' => 'مستلزمات الأمومة - تنظيم الرضيع',
        'mother.popular' => 'مستلزمات الأمومة - الأكثر طلبا',
        'mother.essentials' => 'مستلزمات الأمومة - أساسيات الرضع',
        'mother.new_arrivals' => 'مستلزمات الأمومة - وصل حديثا',
        'care.for_you' => 'الصحة والعناية - من أجلك',
        'care.gentle' => 'الصحة والعناية - عناية لطيفة',
        'care.baby' => 'الصحة والعناية - للرضع',
        'care.bath' => 'الصحة والعناية - الاستحمام',
        'care.daily_health' => 'الصحة والعناية - صحة يومية',
        'care.new_arrivals' => 'الصحة والعناية - وصل حديثا',
        'care.deals' => 'الصحة والعناية - عروض العناية',
        'care.popular' => 'الصحة والعناية - الأكثر طلبا',
        'accessories.for_you' => 'الاكسسوارات - من أجلك',
        'accessories.bags' => 'الاكسسوارات - شنط صغيرة',
        'accessories.hats' => 'الاكسسوارات - قبعات وربطات',
        'accessories.hair' => 'الاكسسوارات - اكسسوارات شعر',
        'accessories.glasses' => 'الاكسسوارات - نظارات',
        'accessories.popular' => 'الاكسسوارات - الأكثر طلبا',
        'accessories.today' => 'الاكسسوارات - اكسسوارات اليوم',
        'accessories.new_arrivals' => 'الاكسسوارات - وصل حديثا',
        'shoes.for_you' => 'الأحذية - من أجلك',
        'shoes.girls' => 'الأحذية - بناتي',
        'shoes.boys' => 'الأحذية - ولادي',
        'shoes.deals' => 'الأحذية - عروض الأحذية',
        'shoes.new_arrivals' => 'الأحذية - وصل حديثا',
        'messages.recommended' => 'الرسائل - أشياء قد تعجبك',
    ],
];
